name: Robô KMM - Webhook (De Hora em Hora)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  executar_robo:
    # Mudança importante: Usando ubuntu-22.04 para evitar o erro do libasound2
    runs-on: ubuntu-22.04

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar Chromium e Dependências do Linux
        run: python -m playwright install --with-deps chromium

      - name: Executar Automação KMM com Monitor Virtual (Xvfb)
        env:
          KMM_USER: ${{ secrets.KMM_USER }}
          KMM_PASS: ${{ secrets.KMM_PASS }}
          URL_WEBHOOK: ${{ secrets.URL_WEBHOOK }}
        run: |
          xvfb-run --server-args="-screen 0 1920x1080x24" python acesso_kmm.py
